# Site settings
title: Solace Samples Javascript
summary: These tutorials get you up to speed sending and receiving messages with Solace technology.
baseurl: "/solace-samples-javascript" # the subpath of your site, e.g. /solace-samples-java
repository: https://github.com/SolaceSamples/solace-samples-javascript

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links
links-community: http://dev.solace.com/community/
links-downloads: http://dev.solace.com/downloads/
links-get-started-javascript: http://dev.solace.com/get-started/javascript-tutorials/
links-tech-other: http://dev.solace.com/tech/#other
docs-vmr-setup: http://docs.solace.com/Solace-VMR-Set-Up/Setting-Up-VMRs.htm
docs-core-concepts: http://docs.solace.com/Features/Core-Concepts.htm
docs-session-events: http://docs.solace.com/Solace-Messaging-APIs/Creating-Client-Sessions-1.htm#Handle-Sess-Events
docs-api-reference: http://docs.solace.com/API-Developer-Online-Ref-Documentation/js/index.html
docs-semp: http://docs.solace.com/SEMP/Using-SEMP-to-Manage-and-Monitor-Routers.htm
docs-topic-mapping: http://docs.solace.com/Features/Core-Concepts.htm#topic-queue-mapping

#----------------------------------------------------
# Generally don't modify items below this point
url: "solacesamples.github.io" # the base hostname & protocol for your site

# Google services
google_analytics: UA-3921398-7

# Build settings
markdown: kramdown

collections:
  tutorials:
    output: true
    permalink: /:path/
