# Site settings
title: Solace Samples Javascript
summary: These tutorials get you up to speed sending and receiving messages with Solace technology.
baseurl: "/solace-samples-javascript"
repository: https://github.com/SolaceSamples/solace-samples-javascript

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links
links-downloads: http://dev.solace.com/downloads/
links-community: http://dev.solace.com/community/
docs-vmr-setup: http://docs.solace.com/Solace-VMR-Set-Up/Setting-Up-VMRs.htm
docs-core-concepts: http://docs.solace.com/Features/Core-Concepts.htm
docs-session-events: http://docs.solace.com/Solace-Messaging-APIs/Creating-Client-Sessions-1.htm#Handle-Sess-Events
#----------------------------------------------------
# Generally don't modify items below this point
url: "solacesamples.github.io" # the base hostname & protocol for your site

# Google services
google_analytics: UA-3921398-7

# Build settings
markdown: kramdown

collections:
  tutorials:
    output: true
    permalink: /:path/
